services:
  db:
    image: postgres:15-alpine
    container_name: expense-tracker-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: expense_tracker
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nest-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    environment:
      - PORT=5000
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/expense_tracker
    ports:
      - '5000:5000'

volumes:
  postgres_data:
