version: '3'

services:
  nest-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - PORT=5000
    ports:
      - '5000:5000'

  db:
    image: postgres:15-alpine
    container_name: expense-tracker-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
